### ISSUE TITLE
[Feature] Support of multimatch in normalize definitions

### ISSUE THREAD

**Issue by kewwwa** [cthrax/gulp-bower-normalize#10]
Hi,

Could it be possible to match files against [multimatch](https://github.com/sindresorhus/multimatch) in normalize definitions, like in [main-bower-files](https://github.com/ck86/main-bower-files) ?
It would be especially usefull when dealing with various font file extensions.

Best regards,

Thibaut

**Comment by cthrax** [comment]
It could be done. To keep backwards compatibility, it'd have to be an array within an array, so something like:
```json
"normalize": {
       "js": "*.js",
        "css": [["*", "!*.ext"], "*.css"]
}
```

Just add an if around https://github.com/cthrax/gulp-bower-normalize/blob/master/index.js#L113 to check if glob is an array. If it's an array, use globby, otherwise use minimatch. Wrap some tests around it, update the dependencies to include globby and you should be golden. I'd definitely take the PR.

**Comment by kewwwa** [comment]
Why not matching directly against multimatch ?
I can't think of any backward compatibility issue, could you give me examples ?
minimatch can match "!*.ext" while multimatch needs ["*", "!*.ext] but who's doing things like that ?
I know it could be a breaking change in some odd cases, maybe 1.1 version is coming ?

**Comment by cthrax** [comment]
Truthfully, I'm not familiar with the differences between the libraries, which is why I suggested the backwards compatible path. Perhaps you're right though that a 1.1 would cover the change. Wrap a few tests with the multi-match format and make the dependency change and I'll make the release.

**Comment by kewwwa** [comment]
It could enable wider possibilities but I'm not able to find relevant ones... Am I contradictory ? n_n'
Actually I thought that would solve my problem of "fonts" dependencies but what I needed is a normalize override for "**/fonts/*" with checkPath enabled. Maybe "fonts" file is a more concrete sample for [checkPath option](https://github.com/cthrax/gulp-bower-normalize#optionscheckpath) ?
I didn't think of possible performance flaws, as multimatch is making more things it could be slower than minimatch. Searching deeper, I found [micromatch](https://www.npmjs.com/package/micromatch#benchmarks) which is a faster than minimatch, with multimatch patterns support !
I have some tests to do, I'll come back with tests and a PR soon :]

**Comment by cthrax** [comment]
You might also look at using the normalizeMulti feature, as outlined in the example file. This allows you to define one pattern to match multiple dependencies. So if dep1, dep2, and dep3 have a font pattern that is needed, then you can just have a list of [dep1, dep2, dep3] and the "font" pattern.

That's a separate discussion from adding micromatch, or some other multimatch functionality, but just thought I would point it out.
