### ISSUE TITLE
Added `main-bower-files` as a dependency in package.json

### ISSUE THREAD

**Issue by nathanbrauer** [cthrax/gulp-bower-normalize#11]
README.md includes the following:

> ##USAGE
> Designed to work with [main-bower-files](https://github.com/ck86/main-bower-files) as so:

...but `main-bower-files` isn't set as a dependency.

**Comment by cthrax** [comment]
It's designed to work that way, but has zero requirements to do so. As long as it receives a list of files in a format it can deal with, it will normalize the paths.
