### ISSUE TITLE
`typeTop` options flag not working

### ISSUE THREAD

**Issue by mikemimik** [cthrax/gulp-bower-normalize#12]
There isn't a test in this project for that flag so I'm wondering if something was overlooked? The flag seems to have no affect on the folder structure but I could very-well be doing something incorrectly.

I have no `overrides` in my `bower.json` file, simply a list of dependencies. 
```javascript
var bower = require('main-bower-files');
var bowerNorm = require('gulp-bower-normalize');
var DEST = { libs: './build/libs/' };

gulp.task('compile-bower', function () {
  return gulp.src(bower(), { base: './bower_components' })
    .pipe(bowerNorm({ typeTop: true })
    .pipe(gulp.dest(DEST.libs));
});
```
Once the task finishes I get a directory structure as follows:
```
/build
└── libs
    ├── bootstrap
    │   ├── js
    │   │   └── bootstrap.js
    │   └── less
    │       └── bootstrap.less
    ├── bootstrap-calendar
    │   ├── css
    │   │   └── calendar.css
    │   └── js
    │       └── calendar.js
    ├── jquery
    │   └── js
    │       └── jquery.js
    ├── moment
    │   └── js
    │       └── moment.js
    └── underscore
        └── js
            └── underscore.js
```
However it should be:
```
/build
└── libs
    ├── css
    │   └── bootstrap-calendar
    │       └── calendar.css
    ├── js
    │   ├── bootstrap
    │   │   └── bootstrap.js
    │   ├── bootstrap-calendar
    │   │   └── calendar.js
    │   ├── jquery
    │   │   └── jquery.js
    │   ├── moment
    │   │   └── moment.js
    │   └── underscore
    │       └── underscore.js
    └── less
        └── bootstrap
            └── bootstrap.less
```

**Comment by mikemimik** [comment]
Solved problem:

After PR (aa8014b79ff9fc58bde455870604e3fdfbf9d7de) was commited, there was no version bump to the package. The package version on NPM is still `1.0.6` and this repo is still `1.0.6` despite there are changes here.

Solution is to `npm install cthrax/gulp-bower-normalize` and pull directly from github repo. 

Please consider bumping the package version and re-publishing to npm for more concise solution.

**Comment by cthrax** [comment]
Actually, I haven't pushed a new release with these changes because of the lack of test. If you'd be willing to write up a test that demonstrates this working, since you understand the use case, I can make the release.

**Comment by mikemimik** [comment]
@cthrax done and done. Let me know what you think.

**Comment by cthrax** [comment]
Thanks for the help! New version should be published. I upped the dependency versions, so I also upped the minor rev, just in case you don't have that wildcarded.

Cheers!
