### ISSUE TITLE
Throw error if > 1 same globs to normalize

### ISSUE THREAD

**Issue by sunlix** [cthrax/gulp-bower-normalize#15]
Hi,

I am new in using your gulp plugin and I hit your described potential bug:
https://github.com/cthrax/gulp-bower-normalize/blob/master/index.js#L104

could you provide a patch with throwing an error if there are > 1 same defined globs in the normalize property?
Maybe you could improve your documentation with this?

I think any other newby could hit that behavior if they don't caution about that like me. :D

Thank you for your effort and sharing this tool :)

regards,
Sven

**Comment by cthrax** [comment]
I'd happily take a pull request on this.

**Comment by sunlix** [comment]
Based on my research the main problem is that after `require(bowerJson)` the duplicate JSON-keys under `'normalize'` aren't present anymore.
From here the last already won the race.

given `normalize` object
````
"normalize": {
  ".": "**/*.scss",
  ".": "**/*.js"
}
````

tried to make the parsed JSON visible via console like `console.log(JSON.stringify(require(bowerJson)));`.
The output only shows the property `".": "**/*.js"`

Do you know any JSON-linter which respects duplicates keys?
maybe we only can update the documentation to inform users on this behavior?

**Comment by cthrax** [comment]
I've never used it, you might give this a try though. https://github.com/zaach/jsonlint . It produces an error upon receiving duplicate keys, with the name of the duplicate key. If we do go this route I think it makes sense for this to be a warning since we're validating the whole of the bower.json file. And we need to be careful not to increase the processing time too much.

**Comment by sunlix** [comment]
`jsonlint` is not an option to validate a JSON file on duplicate keys.
They have an issue since 2011 on that topic > https://github.com/zaach/jsonlint/issues/13
I've reproduced this behavior without any error message on duplicate keys, as well the default JSON.parse() behavior.
I think we only can drop an information in the README.md to point out the behavior as a frequently done mistake.

**Comment by cthrax** [comment]
Fair enough, I'm good with that.

**Comment by cthrax** [comment]
Thanks for the contributions!
