### ISSUE TITLE
https://github.com/advisories/GHSA-jf85-cpcp-j695

### ISSUE THREAD

**Issue by jssuttles** [cthrax/gulp-bower-normalize#19]
gulp-util is deprecated and one of its dependencies has a security vulnerability
proposed: https://github.com/cthrax/gulp-bower-normalize/pull/18

**Comment by jssuttles** [comment]
@cthrax would you mind publishing the package?

**Comment by cthrax** [comment]
@jssuttles running locally it looked like gulp-util was still a dependency...

**Comment by cthrax** [comment]
Looking a bit further, it looks like gulp depends on fsevents 1.x which doesn't work with node 14+. I haven't used this in several years and it doesn't seem like gulp has kept up, unless I'm missing something.

**Comment by jssuttles** [comment]
the tests run with node version 10.
Version 3 of gulp doesn't run in later versions of node, I believe.

code/gulp-bower-normalize [master●] » npm ls gulp-util
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
gulp-bower-normalize@1.1.1 [yada yada]/code/gulp-bower-normalize
└── (empty)

**Comment by jssuttles** [comment]
To update to gulp 4: https://github.com/cthrax/gulp-bower-normalize/pull/20

**Comment by jssuttles** [comment]
Looks like the github action was created but it hasn't run yet because a release hasn't been created, yet?

**Comment by cthrax** [comment]
@jssuttles you're right. Sorry about that, we should be all good now, after some trial and error, with version 1.1.3.

**Comment by jssuttles** [comment]
No problem. Thank you very much for the work on this package!

**Comment by cthrax** [comment]
Glad it's still useful! I actually moved away from it several years ago as I shifted away from gulp to angular-cli/webpack for my tool chain.
