### ISSUE TITLE
Add an option to flatten the folder structure

### ISSUE THREAD

**Issue by xt0rted** [cthrax/gulp-bower-normalize#4]
I'm in the process of moving my dependencies over to bower & gulp and this plugin has helped a lot. One of the issues I'm having though is I'd much rather the folder structure be something like `/content/js/jquery.js` instead of `/content/jquery/js/jquery.js`.

I was able to get the folder structure I wanted by making this change.
``` js
if (options.flatten) {
    file.path = Path.join(file.cwd, file.base, type, components.filename);
} else {
    file.path = Path.join(file.cwd, file.base, components.packageName, type, components.filename);
}
```
Is this something you'd like to add in? I can send a PR if you'd like.

**Comment by cthrax** [comment]
Sure, I'll take a PR on that. Sounds a little dangerous to me, but I can warn about that I suppose. By dangerous I mean, I would worry about the case of "library1/main.js" and "library2/main.js". Now you get content/js/main.js, but which one is it?

**Comment by xt0rted** [comment]
I was thinking the same thing, in fact there's a [comment in the code](https://github.com/cthrax/gulp-bower-normalize/blob/760a7653e124a88eb2a439d8eeaf5f0a9db77533/index.js#L63) similar to this. At the moment none of my dependencies have duplicate names (angularjs, bootstrap, fontawesome, jquery) but I can see where this could become a problem for some.

**Comment by cthrax** [comment]
Yeah, that's the danger with flattening I guess. (I had forgotten I saw that case, I really ought to log a warning or something there).

**Comment by xt0rted** [comment]
When I run the unit tests they all fail due to the path delimiter (I'm on Windows). Is there a way to make these pass without using `Path.normalize()` in each assertion? At the moment that's what I did. I also duplicated the 6 tests that verify each dependency in the `bower.json` file and all are passing.

**Comment by cthrax** [comment]
You might be able to put Path.normalize in the assertNormalized method. Otherwise, there's not really a way around it.

**Comment by xt0rted** [comment]
Any chance of a new release now that this was added in?

**Comment by cthrax** [comment]
Sorry, I thought I had already done that. 1.0.4 away. Cheers!

**Comment by xt0rted** [comment]
thanks!
