### ISSUE TITLE
Add relative path matching option

### ISSUE THREAD

**Issue by YHuard** [cthrax/gulp-bower-normalize#6]
Hi! Thanks for this great plugin!

But it would be even greater if we could match the relative path of a file instead of just its filename. For example, I'm trying to keep bootstrap sass folder structure (with mixins inside a folder called "mixins") and to achieve that, I do:

```json
"overrides": {
    "bootstrap-sass-official": {
      "main": ["**/*.js", "**/*.scss", "**/*.eot", "**/*.svg", "**/*.ttf", "**/*.woff", "**/*.woff2"],
      "normalize": {
        "fonts": ["**/*.eot", "**/*.svg", "**/*.ttf", "**/*.woff", "**/*.woff2"],
        "scss/mixins": "**/mixins/*.scss"
      }
    }
  }
```

I had to edit your index.js to make it work. Instead of passing the filename to minimatch, I pass the relative path. Could you add this functionality to your plugin? 

To avoid BC, just add an optional boolean parameter and check it before calling minimatch

Thanks

**Comment by cthrax** [comment]
Go ahead and create a PR, we'll see what we get from there.

**Comment by YHuard** [comment]
I can't while I'm at work but I will do it later today

**Comment by cthrax** [comment]
I'll look for it then.

**Comment by cthrax** [comment]
Tagged and published.
