### ISSUE TITLE
Add some common normalizations

### ISSUE THREAD

**Issue by Koed00** [cthrax/gulp-bower-normalize#8]
Most libraries expect their fonts and images to live in a common folder, not in folders based on their extension.  I find myself writing the same overwrites over and over again. 
Would it benefit the plugin to support these normalization's as standard?

```
      "normalize": {
        "fonts": [
          "*.otf",
          "*.eot",
          "*.svg",
          "*.ttf",
          "*.woff",
          "*.woff2"
         ]
    }
```
```
   "normalize": {
    "img": [
       "*.gif",
       "*.png",
       "*.jpg",
      ]
    }

```

**Comment by cthrax** [comment]
That's a very interesting idea. So providing some method to add constants to the configuration file so that  common options are included.

Something like:

```javascript
"normalize": {
   "img": [ "_normalize_img_defaults_"]
}
```

Which will expand to some predefined set of image wildcards. And in the case you mention of images and fonts together, you could have:

```javascript
"normalize": {
   "img": [ "_normalize_img_defaults_", "_normalize_font_defaults_"]
}
```

You'd still be writing the same overrides, but the amount of writing has been reduced.

As to the statement about not organizing by filetype, the expectation for the use of this plugin is that assets are moved as part of a build process. So if images, css and fonts are supposed to be in the same folder, then there is a copy command that takes care of that. The behavior can obviously be customized to your need of putting images, css and fonts into the same folder as outlined above, but I don't plan on making that a default behavior.

**Comment by Koed00** [comment]
The problem becomes apparent when you start normalizing font libraries like Fontawesome and Glyphicons. They all include half a dozen or more file extensions that live in the same folder. Without the override they get split in to half a dozen directories. It's safe to say that if it came from a 'fonts' folder, it wants to stay there. 

Maybe the solution , more in line with your philosophy, would be to allow for global overrides. Instead of having to add them for each package, you could just define that all *.ttf files will always normalize to a font folder and for example *.map files to the js folder.

**Comment by cthrax** [comment]
Global Overrides would be an interesting solution. I think I like it, but there is one case I'm not sure would be desirable.

```javascript
"overrides": {
    "normalizeGlobalOverrides": {
         "font": ["*.ttf", "*.woff2"]
    },
    "mobileFontPackage": {
         "mobile-font": ["*.ttf", "*.woff2"]
    }
```

This will put a "font" folder in mobileFontPackage as well. I'm not sure if that's a real issue and could probably be handled by adding "font: ['*.nofiles']", now there would just be an empty "font" folder.

What do you think?

**Comment by Koed00** [comment]
I've been trying to find a real world example of when this would be an issue, but I can't really find one.
Such a case can probably be handled by the user by piping the `font` folder to `mobile-font` after normalization and leaving out the `mobile-font` override altogether.

**Comment by cthrax** [comment]
I've been thinking about this a bit more, I'm not sure how you would apply globals that weren't truly global. For instance,

```javascript
"overrides": {
   "normalizeGlobalOverrides": {
      "img": ["*.png", "*.jpg"]
   },
   "javascriptOnlyPackage": {
      "js": "*.js"
   }
}
```

In this scenario, the javascriptOnlyPackage will end up with an img folder as well, which likely have nothing in it, but could end up with other folders. This defeats the cleanliness I'm looking for from the output of this plugin, particularly given the mess that git-based bower installs produce.

There are two solutions I can think of at this point. One, use the constants as I outlined above. Or two, allow an override to apply to multiple packages.

An example of number two would be something like:

```javascript
"overrides": {
    "normalizeMulti": {
        "packages": ["fontAwesome", "fooPackage"],
        "overrides": {
            "font": ["*.ttf", "*.woff2"] // Possibly make these the constants as outlined above as well
        }
    }
}
```

**Comment by Koed00** [comment]
Personally I really like the second option. Overrides for multiple packages. It's clean, simple and fixes my original issue where my bower.json had over a dozen font overrides.

**Comment by cthrax** [comment]
That shouldn't be too hard to implement, just see if that multi exists, pull it out of the rest of the overrides list and overlay any existing overrides on top of that. I'll see if I can get to it this weekend, but if you get the itch to throw it in, by all means send me a PR.

**Comment by cthrax** [comment]
Alright, I got it added. Hope you enjoy it!

**Comment by Koed00** [comment]
I was gone for the weekend, but this is a nice coming home surprise. I'll give it a go today. 
Thanks so much for your work.This will clean up my Bower messes nicely.
